FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY backend/client/pom.xml .
COPY backend/client/src ./src
RUN ./mvnw clean package -DskipTests
EXPOSE 8080
CMD ["java","-jar","target/client-0.0.1-SNAPSHOT.jar"]
