FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY backend/rss/pom.xml .
COPY backend/rss/src ./src
RUN ./mvnw clean package -DskipTests
EXPOSE 9000
CMD ["java","-jar","target/rss-0.0.1-SNAPSHOT.jar"]
